CFLAGS=-Wall -g

all: ex1.c ex3.c ex5.c ex6.c ex9.c ex12.c ex13.c ex14.c
	make ex1
	make ex3
	make ex5
	make ex6
	make ex9
	make ex12
	make ex13
	make ex14
clean:
	rm -f ex1
	rm -f ex3
	rm -f ex5
	rm -f ex6
	rm -f ex9
	rm -f ex12
	rm -f ex13
	rm -f ex14
